### ISSUE TITLE
CPqD Queue Problem

### ISSUE THREAD

**Issue by balotr** [CPqD/ofsoftswitch13#281]
Hi I want to declare queue problem again. From mininet one cannot add queue.

These are the guys having same problem:
https://github.com/CPqD/ofsoftswitch13/issues/259
https://github.com/CPqD/ofsoftswitch13/issues/244
https://github.com/CPqD/ofsoftswitch13/issues/224
https://github.com/CPqD/ofsoftswitch13/issues/222
https://github.com/CPqD/ofsoftswitch13/issues/104
https://stackoverflow.com/questions/33677006/adding-queues-to-switch-of-ofsoftswitch13-implementation-doesnt-work

Here is how I encountered problem:

I wanted to add queue with dpctl utility. When I issue 'dpctl --help', there exists such line:
`SWITCH queue-mod PORT QUEUE BW         adds/modifies queue`
After issuing mininet command `sudo mn --mac --switch user --controller remote -x` my user switch connects to controller. I can understand connection from controllers screen and from command `ofprotocol tcp:127.0.0.1:6634`. At output of ofprotocol command datapath id is written with connected message.
When I issue  `dpctl tcp:localhost:6634 queue-mod 1 1 80` message, on the screen I get following message:
```
SENDING (xid=0xF0FF00F0):
expmodqueue{port="1", queue={q="1", props=[minrate{min rate="80"}]}}


RECEIVED (xid=0xF0FF00F0):
error{type="QUEUE_OP_FAILED", code="EPERM", dlen="56"}
```
To understand if I am doing sth wrong I changed port number and issued command `sudo dpctl unix:/tmp/s1 queue-mod 3 1 100` Here is the output:
```
SENDING (xid=0xF0FF00F0):
expmodqueue{port="3", queue={q="1", props=[minrate{min rate="100"}]}}


RECEIVED (xid=0xF0FF00F0):
error{type="QUEUE_OP_FAILED", code="BAD_PORT", dlen="56"}
```
I also tried no slicing option but that broke my connection with controller.

Here is what I did so far to solve problem:

In source code of CPqD there exists 2 location where we get type="QUEUE_OP_FAILED", code="EPERM" error. It is in 'udatapath/dp_ports.c' file in dp_ports_handle_queue_modify() function (Starting Line 1017). Here is the code:
```
dp_ports_handle_queue_modify(struct datapath *dp, struct ofl_exp_openflow_msg_queue *msg,
        const struct sender *sender UNUSED) {
    // NOTE: assumes the packet queue has exactly one property, for min rate
    struct sw_port *p;
    struct sw_queue *q;

    int error = 0;

    p = dp_ports_lookup(dp, msg->port_id);
    if (PORT_IN_USE(p)) {
        q = dp_ports_lookup_queue(p, msg->queue->queue_id);
        if (q != NULL) {
            /* queue exists - modify it */
            error = netdev_change_class(p->netdev,q->class_id,
                                 ((struct ofl_queue_prop_min_rate *)msg->queue->properties[0])->rate);
             if (error) {
                 VLOG_ERR(LOG_MODULE, "Failed to update queue %d", msg->queue->queue_id);
                 return ofl_error(OFPET_QUEUE_OP_FAILED, OFPQOFC_EPERM);
             }
             else {
                 ((struct ofl_queue_prop_min_rate *)q->props->properties[0])->rate =
                         ((struct ofl_queue_prop_min_rate *)msg->queue->properties[0])->rate;
             }

        } else {
            /* create new queue */
            error = port_add_queue(p, msg->queue->queue_id,
                                       (struct ofl_queue_prop_min_rate *)msg->queue->properties[0]);
            if (error == EXFULL) {
                return ofl_error(OFPET_QUEUE_OP_FAILED, OFPQOFC_EPERM);
            }

            q = dp_ports_lookup_queue(p, msg->queue->queue_id);
                error = netdev_setup_class(p->netdev,q->class_id,
                                ((struct ofl_queue_prop_min_rate *)msg->queue->properties[0])->rate);
                if (error) {
                    VLOG_ERR(LOG_MODULE, "Failed to configure queue %d", msg->queue->queue_id);
                    return ofl_error(OFPET_QUEUE_OP_FAILED, OFPQOFC_BAD_QUEUE);
                }
        }

    } else {
        VLOG_ERR(LOG_MODULE, "Failed to create/modify queue - port %d doesn't exist", msg->port_id);
        return ofl_error(OFPET_QUEUE_OP_FAILED, OFPQOFC_BAD_PORT);
    }
```
Since we are creating new queue I focused create new queue part and followed the code. It comes to following function:
```
port_add_queue(struct sw_port *p, uint32_t queue_id,
               struct ofl_queue_prop_min_rate * mr)
{
    if (queue_id >= p->max_queues) {
        return EXFULL;
    }

    if (p->queues[queue_id].port != NULL) {
        return EXFULL;
    }

    return new_queue(p, &(p->queues[queue_id]), queue_id, queue_id, mr);
}
```
In this function, when I command(/**/) first if I get dpctl: Error during transaction. But when I command second if statement I get exactly the same error with the one when I issue dpctl command. BINGO! Therefore, problem is at first if statement. Since max_queue parameter is below 1 in that port we cannot add queue. I searched ports max_queues parameter. It is uint16_t type and initialized with following statement in new_port function:

`max_queues = MIN(max_queues, NETDEV_MAX_QUEUES);`

NETDEV_MAX_QUEUES value is 8 and #defined with preprocessor command)

new_port is called in 2 functions in code:
```
dp_ports_add(struct datapath *dp, const char *netdev)
{
    uint32_t port_no;
    for (port_no = 1; port_no < DP_MAX_PORTS; port_no++) {
        struct sw_port *port = &dp->ports[port_no];
        if (port->netdev == NULL) {
            return new_port(dp, port, port_no, netdev, NULL, dp->max_queues);
        }
    }
    return EXFULL;
}
#endif /* OF_HW_PLAT */

int
dp_ports_add_local(struct datapath *dp, const char *netdev)
{
    if (!dp->local_port) {
        uint8_t ea[ETH_ADDR_LEN];
        struct sw_port *port;
        int error;

        port = xcalloc(1, sizeof *port);
        eth_addr_from_uint64(dp->id, ea);
        error = new_port(dp, port, OFPP_LOCAL, netdev, ea, 0);
        if (!error) {
            dp->local_port = port;
        } else {
            free(port);
        }
        return error;
    } else {
        return EXFULL;
    }
}
```

When I change new_port(dp, port, OFPP_LOCAL, netdev, ea, 0); or return new_port(dp, port, port_no, netdev, NULL, dp->max_queues); statements I lose connection with controller. Also I lose connection when I make statement max_queues = MIN(max_queues, NETDEV_MAX_QUEUES); to max_queues= 5;

Of course I run following commands after every change in source code:
```
$ ./boot.sh
$ ./configure
$ make
$ sudo make install 
```
Is there a documantation or UML diagrams that explains code further? I would be greatful if I can help you and if you help me :) Sorry for long and boring explanation

**Comment by ederlf** [comment]
Hi, sorry about that. That problem and a possible solution was pointed a long time ago by @nikchez01 and I should have addressed by then. 

The problem was throwing an error when an interface had no queues configured.

Please check if 7075dec54d877b497de50b78d230ffee6c14474d fixes your problem. 
I tested by adding the first queue you tried and it went fine.

**Comment by balotr** [comment]
Hi @ederlf 

Thanks for your help but it did not solve my problem. My problem occurs when I add queue at the beginning of simulation (no queue configured). At logs I can get the following output when I try to add my queue to wrong port:

`Aug 16 19:22:39|00001|dp_ports|ERR|Failed to create/modify queue - port 3 doesn't exist`

but I cannot get any error when I try to add a queue to existing port.

**Comment by ederlf** [comment]
I do not understand what is the problem now. 
You are trying to add a queue to a port that does not exist, so it returns an error. 

> but I cannot get any error when I try to add a queue to existing port.

Is it not what it is supposed to happen? Are you still getting an error? 
Remember you need to use remove --no-slicing option.

In Mininet, you can do something like this to remove that option:

``
self.addSwitch( 's3', cls=UserSwitch, dpopts='') 
``

**Comment by balotr** [comment]
Thanks, my problem is solved when I remove no slicing option.

**Comment by ederlf** [comment]
Thanks for letting me know :-)
